# https://doc.traefik.io/traefik/setup/kubernetes/

ports:
  web:
    port: 8000
    nodePort: 30000
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    port: 8443
    nodePort: 30001

api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-stg-local.chammanganti.dev`)
    entryPoints:
      - websecure
    middlewares:
      - name: dashboard-auth

ingressClass:
  enabled: false

providers:
  kubernetesIngress:
     enabled: false
  kubernetesGateway:
     enabled: true

gateway:
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:
      port: 8443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: dashboard-tls
          group: ""

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: false
