apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.trustedProxies }}
        - {{ . }}
        {{- end }}
